Traceback (most recent call last):
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular/train.py", line 15, in <module>
    X_train, y_train, X_test, y_test = get_preprocessed_adult_data()
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular/data_loading.py", line 37, in get_preprocessed_adult_data
    train, test = load_adult_files()
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular/data_loading.py", line 9, in load_adult_files
    train = pd.read_csv('tabular_data/adult.data', names=column_names, index_col=False, na_values=[' ?', '?'])
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/andrea/PycharmProjects/data_exfiltration_tabular_venv/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'tabular_data/adult.data'